CXX := g++
CXXFLAGS := -std=c++23 -Os -static -ffunction-sections -fdata-sections -I/usr/local/include -I/usr/include -I/usr/include/luajit-2.1 -Isrc
LDFLAGS := -L/usr/local/lib -L/usr/lib -static -Wl,--export-dynamic

# Libraries
LIBS := -lluajit-5.1 -Wl,--whole-archive -lreadline -lncurses -lsqlite3 -lvterm -Wl,--no-whole-archive -ldatachannel -lboost_system -lpthread -ldl -lssl -lcrypto -lnice -lglib-2.0 -lgthread-2.0 -lintl

# Fennel Source Management
# Find all .fnl files in src/
FNL_SRCS := $(wildcard src/*.fnl)

# 1. Fennel -> Lua
# src/fennel.lua is a special case (copied from system), so we append it manually.
LUA_GEN := $(FNL_SRCS:.fnl=.lua) src/fennel.lua

# 2. Lua -> Bytecode
BC_GEN := $(LUA_GEN:.lua=.bc)

# 3. Bytecode -> C++ Source (data) and Header (declarations)
# We generate src/foo_bc.cc for the data array and src/foo_bc.h for externs.
BC_CC := $(BC_GEN:.bc=_bc.cc)
BC_HDRS := $(BC_GEN:.bc=_bc.h)

# C++ Sources
# We include the generated bytecode C++ files in the build.
SRCS := src/main.cc src/bindings.cc src/args.cc src/lua.cc $(BC_CC)
OBJS := $(SRCS:.cc=.o)

.PHONY: all clean debug_vars

all: 9sh

debug_vars:
	@echo "FNL_SRCS: $(FNL_SRCS)"
	@echo "LUA_GEN: $(LUA_GEN)"
	@echo "BC_GEN: $(BC_GEN)"
	@echo "BC_CC: $(BC_CC)"
	@echo "BC_HDRS: $(BC_HDRS)"

9sh: $(OBJS) $(BC_HDRS)
	$(CXX) $(CXXFLAGS) -o $@ $(OBJS) $(LDFLAGS) $(LIBS)

# Compile C++ files
# Generic rule for all C++ files
%.o: %.cc
	$(CXX) $(CXXFLAGS) -c -o $@ $<

# Define header dependencies for specific files
src/main.o: $(BC_HDRS)
src/bindings.o: $(BC_HDRS)
src/lua.o: $(BC_HDRS)

# Static Pattern Rules for Fennel Pipeline

# 1. .fnl -> .lua
# Note: src/fennel.lua is handled separately below
src/%.lua: src/%.fnl
	fennel --compile $< > $@

# 2. .lua -> .bc
# All BC files depend on their corresponding Lua file
$(BC_GEN): src/%.bc: src/%.lua
	luajit -b $< $@

# 3. .bc -> .cc (using xxd)
# Explicit static pattern rule
$(BC_CC): src/%_bc.cc: src/%.bc
	xxd -i $< > $@

# 4. .bc -> .h (extern declarations)
# Explicit static pattern rule
$(BC_HDRS): src/%_bc.h: src/%.bc
	@echo "#pragma once" > $@
	@echo "extern unsigned char $(subst /,_,$(subst .,_,$(<:.bc=_bc)))[];" >> $@
	@echo "extern unsigned int $(subst /,_,$(subst .,_,$(<:.bc=_bc)))_len;" >> $@

# Special case for src/fennel.lua
src/fennel.lua:
	cp $(shell which fennel) $@
	sed -i '1d' $@
	sed -i 's/assert(arg, "Using the launcher from non-CLI context; use fennel.lua instead.")/if not arg then return require("fennel") end/' $@

clean:
	rm -f 9sh src/*.o src/*.bc src/*.lua src/fennel.lua src/*_bc.cc src/*_bc.h

