#include <iostream>
#include <vector>
#include <string>
#include <cstring>
#include <luajit-2.1/lua.hpp>
#include <readline/readline.h>
#include <readline/history.h>

// Include the embedded bytecode
#include "boot.h"
#include "fennel.h"

// Forward declaration of the C array generated by xxd
extern unsigned char src_boot_bc[];
extern unsigned int src_boot_bc_len;
extern unsigned char src_fennel_bc[];
extern unsigned int src_fennel_bc_len;

int main(int argc, char** argv) {
    // Basic argument parsing
    std::string eval_script;
    bool execute_flag = false;

    for (int i = 1; i < argc; ++i) {
        if (std::strcmp(argv[i], "-e") == 0 && i + 1 < argc) {
            eval_script = argv[++i];
            execute_flag = true;
        }
    }

    // Initialize Lua
    lua_State* L = luaL_newstate();
    luaL_openlibs(L);

    // Load Fennel compiler (embedded)
    if (luaL_loadbuffer(L, (const char*)src_fennel_bc, src_fennel_bc_len, "fennel.lua") != 0) {
        std::cerr << "Error loading embedded fennel: " << lua_tostring(L, -1) << std::endl;
        return 1;
    }
    // Run fennel chunk to get the module table
    if (lua_pcall(L, 0, 1, 0) != 0) {
        std::cerr << "Error initializing fennel: " << lua_tostring(L, -1) << std::endl;
        return 1;
    }
    // Now the fennel table is on top of the stack.
    // Let's set it to package.loaded.fennel and also global 'fennel'
    lua_pushvalue(L, -1);
    lua_setglobal(L, "fennel");
    lua_getglobal(L, "package");
    lua_getfield(L, -1, "loaded");
    lua_pushvalue(L, -3); // the fennel table
    lua_setfield(L, -2, "fennel");
    lua_pop(L, 2); // pop loaded and package
    // Fennel table is still on top

    // Load the embedded boot script
    // We treat the embedded bytecode as a raw buffer.
    if (luaL_loadbuffer(L, (const char*)src_boot_bc, src_boot_bc_len, "boot.fnl") != 0) {
        std::cerr << "Error loading embedded boot script: " << lua_tostring(L, -1) << std::endl;
        return 1;
    }

    // Initialize the module
    if (lua_pcall(L, 0, 1, 0) != 0) {
         std::cerr << "Error running embedded boot script: " << lua_tostring(L, -1) << std::endl;
         return 1;
    }

    // The boot script returns a table
    lua_setglobal(L, "Boot");

    // Handle -e execution
    if (execute_flag) {
        // fennel.eval(script)
        lua_getglobal(L, "fennel");
        lua_getfield(L, -1, "eval");
        lua_remove(L, -2); // remove fennel table

        lua_pushstring(L, eval_script.c_str());

        if (lua_pcall(L, 1, 0, 0) != 0) {
            std::cerr << "Error executing script: " << lua_tostring(L, -1) << std::endl;
            return 1;
        }
        return 0;
    }

    // REPL
    std::cout << "Welcome to 9sh (Skeletal)" << std::endl;
    char* input;
    while ((input = readline("9sh> ")) != nullptr) {
        if (*input) {
            add_history(input);
            if (luaL_dostring(L, input) != 0) {
                std::cerr << "Error: " << lua_tostring(L, -1) << std::endl;
            }
        }
        free(input);
    }

    lua_close(L);
    return 0;
}
